# Site settings
title: Just a thinker
email: zhimingyuan@126.com	
description: > # this means to ignore newlines until "baseurl:"
  爱生活，爱摄影，一个感性的程序猿。坚持“简单、纯粹才是最好的”。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nkzhimingyuan.github.io" # the base hostname & protocol for your site

github_username:  nkzhimingyuan

# Build settings
markdown: kramdown
